Added 404 NotFound page
peercoin/peercoin.net pull request #173
Opened 2021-02-22 22:18 UTC by michaelkebe

Added a 404 Not Found Page. Fixes #171.

2021-02-22 22:35 UTC, peerchemist commented
Looks good to me. Thanks.

@bananenwilly how about you?

2021-02-23 05:52 UTC, bananenwilly commented
310 lines of new SCSS for a 404 page are not really acceptable

2021-02-23 05:58 UTC, bananenwilly approved these changes

2021-02-23 05:58 UTC, bananenwilly requested changes
reduce SCSS

2021-02-23 06:00 UTC, bananenwilly commented on src/pages/NotFound/NotFound.jsx
> +    <>
nice

2021-02-23 07:16 UTC, bananenwilly approved these changes

2021-02-23 07:16 UTC, merged

2021-02-23 07:16 UTC, bananenwilly commented
@michaelkebe  thanks and welcome 👍🏻