Added gemmer
peercoin/peercoin.net pull request #175
Opened 2021-02-23 23:53 UTC by captainbuckkets

Please review for merge

2021-02-23 23:58 UTC, peerchemist commented
Gemmer is just a mobile wallet, not both mobile/web.

2021-02-24 05:40 UTC, bananenwilly commented
@captainbuckkets please elaborate on why you're putting english strings into French/German translation files. 
English will always serve as backup and does not need to be added to all loc files.

2021-02-24 05:40 UTC, bananenwilly requested changes
clean up translation files
consider commit from chemist

2021-02-24 05:40 UTC, captainbuckkets commented
> @captainbuckkets please elaborate on why you're putting english strings into French/German translation files. 
> English will always serve as backup and does not need to be added to all loc files. 
> 

Because I don't know what I'm doing since it moved to React. Been a whole year

2021-02-24 05:42 UTC, bananenwilly commented
> 
> 
> > @captainbuckkets please elaborate on why you're putting english strings into French/German translation files.
> > English will always serve as backup and does not need to be added to all loc files.
> 
> Because I don't know what I'm doing since it moved to React. Been a whole year

Whoever chose to do it this way left the rest of us with a massive headache.
See https://github.com/peercoin/peercoin.net/pull/166#issuecomment-767650737 for example

2021-02-24 05:43 UTC, captainbuckkets commented
I miss HTML3. I'll try to look tomorrow of i have time

2021-02-24 05:44 UTC, bananenwilly commented
> 
> 
> I miss HTML3. I'll try to look tomorrow if I have tim

2021-02-24 05:44 UTC, bananenwilly commented
oops

2021-02-24 16:48 UTC, peerchemist commented
Link to gemmer should point to the Play Store.

2021-02-24 18:05 UTC, captainbuckkets reviewed
I didn't see EN strings going into DE/FR but did this solve the problem?

2021-02-24 18:07 UTC, bananenwilly commented on public/locales/de/translation.json
> +    "type4": "Mobile Wallet"
^^

2021-02-24 18:07 UTC, bananenwilly commented on public/locales/en-US/translation.json
> +    "type4": "Mobile Wallet"
^^^

2021-02-24 18:07 UTC, bananenwilly commented on public/locales/fr/translation.json
> +    "type4": "Mobile Wallet"
^^^

2021-02-24 18:30 UTC, captainbuckkets reviewed
Updated

2021-02-24 18:40 UTC, bananenwilly approved these changes

2021-03-04 12:48 UTC, merged